# Generated by Django 5.0 on 2023-12-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='status',
            field=models.CharField(choices=[('accept', 'Accepted'), ('decline', 'Declined'), ('open', 'Open')], default='open', max_length=20),
        ),
    ]
