# Generated by Django 5.0 on 2023-12-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0002_pickuprequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='new_ticket_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
