# Generated by Django 5.0 on 2023-12-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0003_pickuprequest_new_ticket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuprequest',
            name='back_image',
            field=models.FileField(upload_to='media/uploads/'),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='front_image',
            field=models.FileField(upload_to='media/uploads/'),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='invoice_copy',
            field=models.FileField(upload_to='media/uploads/'),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='issue_voice',
            field=models.FileField(upload_to='media/uploads/'),
        ),
    ]
