# Generated by Django 5.0 on 2023-12-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0004_alter_pickuprequest_back_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuprequest',
            name='back_image',
            field=models.FileField(upload_to='back_images/'),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='front_image',
            field=models.FileField(upload_to='front_images/'),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='invoice_copy',
            field=models.FileField(upload_to='invoice_copies/'),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='issue_voice',
            field=models.FileField(upload_to='issue_voices/'),
        ),
    ]
